spring.application.name=GachaHub
spring.mvc.view.prefix= /WEB-INF/views/
spring.mvc.view.suffix= .jsp

spring.datasource.url=jdbc:mysql://localhost:3306/gacha
spring.datasource.username=root
spring.datasource.password=2006
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug